name: Android CI

on:
  push:
    branches: [ ci_cd_test ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: ./.github/workflows/ktlint.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      # 💡 1. Gradle Cache (early for faster builds)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Download Gradle dependencies
        run: ./gradlew dependencies

      # ✅ Unit testing
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # ✅ Code coverage
      - name: Run Jacoco
        run: ./gradlew jacocoTestReport

      # ✅ Code quality tools
      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      # ✅ APK build
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # ✅ Comment PR with result (only on PR)
      - name: Comment PR with test results
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            ✅ All checks passed!

      # ✅ Telegram notification
      - name: Notify via Telegram
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot$BOT_TOKEN/sendMessage \
            -d chat_id=$CHAT_ID \
            -d text="✅ CI Passed for $GITHUB_REPOSITORY"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
